functionality:
  name: "copy"
  namespace: "utils"
  version: "dev"
  description: Copy a file
  authors:
    - name: Kevin Verstaen
      roles: [author]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          required: true
          description: File to copy
    - name: Outputs
      arguments:
        - name: "--output"
          alternatives: ["-o"]
          type: file
          direction: output
          default: output
          description: output
  resources:
    - type: bash_script
      path: ./script.sh
platforms:
  - type: nextflow
